# SPDX-License-Identifier: MIT
[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$results=New-Object 'System.Collections.Generic.List[object]'
function Record([string]$Name,[scriptblock]$Test){try{&$Test;$results.Add([pscustomobject]@{name=$Name;status='PASS'})}catch{$results.Add([pscustomobject]@{name=$Name;status='FAIL';error=$_.Exception.Message})}}
Record 'powershell_syntax' {foreach($f in Get-ChildItem $PSScriptRoot -Filter '*.ps1'){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($f.FullName,[ref]$tokens,[ref]$errors)|Out-Null;if($errors.Count){throw "$($f.Name): $($errors[0].Message)"}}}
. (Join-Path $PSScriptRoot 'common.ps1')
Record 'bundle_integrity' {Assert-NxDBundleIntegrity}
Record 'ram_low_path' {$old=${function:Get-NxDRamGiB};try{function Get-NxDRamGiB{return 3.5};$threw=$false;try{Assert-NxDRam ([pscustomobject]@{gates=[pscustomobject]@{minimum_available_ram_gib=6}}) 'test'|Out-Null}catch{$threw=$_.Exception.Message-like'RAM_TOO_LOW:*'};if(-not$threw){throw 'RAM low path did not fail'}}finally{${function:Get-NxDRamGiB}=$old}}
Record 'clean_cache_recovery_safe_path' {$old=${function:Invoke-NxDWslMemoryCommand};$script:memoryCommands=New-Object 'System.Collections.Generic.List[string]';try{function Invoke-NxDWslMemoryCommand {param([string]$Command);$script:memoryCommands.Add($Command);if($Command-eq'dirty'){return 'Dirty: 0 kB'};if($Command-eq'writeback'){return 'Writeback: 0 kB'};return 'vm.drop_caches = 1'};if(-not(Invoke-NxDSafeLinuxCleanCache)){throw 'safe recovery did not run'};if(($script:memoryCommands-join',')-cne'dirty,writeback,drop-clean-cache'){throw "unexpected commands: $($script:memoryCommands-join',')"}}finally{${function:Invoke-NxDWslMemoryCommand}=$old}}
Record 'clean_cache_recovery_preserves_dirty_pages' {$old=${function:Invoke-NxDWslMemoryCommand};$script:dropCalled=$false;try{function Invoke-NxDWslMemoryCommand {param([string]$Command);if($Command-eq'drop-clean-cache'){$script:dropCalled=$true;return 'vm.drop_caches = 1'};if($Command-eq'dirty'){return 'Dirty: 56 kB'};return 'Writeback: 0 kB'};if(-not(Invoke-NxDSafeLinuxCleanCache)-or-not$script:dropCalled){throw 'clean cache was not reclaimed while harmless dirty pages were preserved'}}finally{${function:Invoke-NxDWslMemoryCommand}=$old}}
Record 'clean_cache_recovery_refuses_writeback' {$oldCommand=${function:Invoke-NxDWslMemoryCommand};$oldSleep=${function:Start-Sleep};$script:dropCalled=$false;try{function Invoke-NxDWslMemoryCommand {param([string]$Command);if($Command-eq'drop-clean-cache'){$script:dropCalled=$true};if($Command-eq'dirty'){return 'Dirty: 8 kB'};return 'Writeback: 4 kB'};function Start-Sleep {param($Seconds)};if(Invoke-NxDSafeLinuxCleanCache){throw 'unsafe recovery reported success'};if($script:dropCalled){throw 'drop_caches ran during writeback'}}finally{${function:Invoke-NxDWslMemoryCommand}=$oldCommand;${function:Start-Sleep}=$oldSleep}}
Record 'ram_reclaim_wait_observes_release' {$oldRam=${function:Get-NxDRamGiB};$oldSleep=${function:Start-Sleep};$script:ramReads=0;try{function Get-NxDRamGiB {$script:ramReads++;if($script:ramReads-lt2){return 4.2};return 6.2};function Start-Sleep {param($Seconds)};$cfg=[pscustomobject]@{gates=[pscustomobject]@{minimum_available_ram_gib=6}};$result=Wait-NxDRamAfterCleanCache $cfg 'test' 10;if($result-ne6.2-or$script:ramReads-ne2){throw "RAM release was not observed: result=$result reads=$script:ramReads"}}finally{${function:Get-NxDRamGiB}=$oldRam;${function:Start-Sleep}=$oldSleep}}
Record 'activation_missing_approval_refusal' {$o=& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'run_nxb21_bcd_activation.ps1') 2>&1;$code=$LASTEXITCODE;if($code-ne40-or($o-join' ') -notlike'*OwnerApproved*'){throw "exit=$code output=$($o-join' ')"}}
Record 'activation_missing_receipt_refusal' {$threw=$false;try{Assert-NxDActivationArtifacts (Join-Path $env:TEMP ([guid]::NewGuid().ToString())) 'missing-hash' 'missing-seal'}catch{$threw=$true};if(-not$threw){throw 'missing artifacts admitted'}}
Record 'mock_model_unload_path' {$old=${function:Invoke-RestMethod};$script:mockUri='';try{function Invoke-RestMethod {param($Method,$Uri,$ContentType,$Body,$TimeoutSec);$script:mockUri=$Uri};Invoke-NxDUnload ([pscustomobject]@{runtime=[pscustomobject]@{localai_url='http://mock'};model=[pscustomobject]@{id='qwen_qwen3-4b-instruct-2507'}});if($script:mockUri-cne'http://mock/backend/shutdown'){throw 'wrong unload path'}}finally{${function:Invoke-RestMethod}=$old}}
Record 'loaded_model_state_uses_system' {$old=${function:Invoke-RestMethod};$script:mockUri='';try{function Invoke-RestMethod {param($Method,$Uri,$TimeoutSec);$script:mockUri=$Uri;return [pscustomobject]@{loaded_models=@([pscustomobject]@{id='qwen_qwen3-4b-instruct-2507'})}};$cfg=[pscustomobject]@{runtime=[pscustomobject]@{localai_url='http://mock'};model=[pscustomobject]@{id='qwen_qwen3-4b-instruct-2507'}};if($null-eq(Get-NxDLoadedState $cfg)-or$script:mockUri-cne'http://mock/system'){throw 'loaded model was not found through /system'}}finally{${function:Invoke-RestMethod}=$old}}
Record 'consumed_holdout_refusal' {$receipt=Join-Path $root 'reports/nxb21/d-model-evaluation-receipt-v1.json';if(-not(Test-Path $receipt)){throw 'terminal receipt missing'};$threw=$false;try{Assert-NxDHoldoutNotConsumed}catch{$threw=$_.Exception.Message-like'HOLDOUT_ALREADY_CONSUMED*'};if(-not$threw){throw 'consumed holdout was admitted'}}
Record 'activation_receipt_pass' {Assert-NxDActivationReceipt ([pscustomobject]@{holdout_consumed=$true;cases_completed=168;DExitDecision='PASS';critical=[pscustomobject]@{percent=100};suitability='SUITABLE';runtime_postcheck='PASS'})}
foreach($bad in @(
  @{n='holdout_not_consumed';p=@{holdout_consumed=$false;cases_completed=168;DExitDecision='PASS';critical=@{percent=100};suitability='SUITABLE';runtime_postcheck='PASS'}},
  @{n='critical_failure';p=@{holdout_consumed=$true;cases_completed=168;DExitDecision='PASS';critical=@{percent=99};suitability='SUITABLE';runtime_postcheck='PASS'}},
  @{n='d_failed';p=@{holdout_consumed=$true;cases_completed=168;DExitDecision='FAIL';critical=@{percent=100};suitability='INSUFFICIENT';runtime_postcheck='PASS'}})){
  Record ('activation_refuses_'+$bad.n) {$threw=$false;try{Assert-NxDActivationReceipt ([pscustomobject]$bad.p)}catch{$threw=$true};if(-not$threw){throw 'gate admitted invalid receipt'}}
}
Record 'wrong_digest_refusal' {$cfg=Get-NxDConfig;$cfg.d_source_digest='0000000000000000000000000000000000000000000000000000000000000000';$threw=$false;try{Test-NxDSourceManifest $cfg|Out-Null}catch{$threw=$true};if(-not$threw){throw 'wrong digest admitted'}}
Record 'actual_source_manifest_passes' {$cfg=Get-NxDConfig;$digest=Test-NxDSourceManifest $cfg;if($digest-cne[string]$cfg.d_source_digest){throw "aggregate digest mismatch: $digest"}}
Record 'container_health_shapes' {$without=[pscustomobject]@{State=[pscustomobject]@{Status='running';OOMKilled=$false}};$with=[pscustomobject]@{State=[pscustomobject]@{Status='running';OOMKilled=$false;Health=[pscustomobject]@{Status='healthy'}}};$bad=[pscustomobject]@{State=[pscustomobject]@{Status='running';OOMKilled=$false;Health=[pscustomobject]@{Status='unhealthy'}}};if(-not(Test-NxDContainerHealthy $without)-or-not(Test-NxDContainerHealthy $with)-or(Test-NxDContainerHealthy $bad)){throw 'Docker health shape handling failed'}}
Record 'active_job_query_matches_enum' {$old=${function:Invoke-NxDNative};$script:jobArgs=@();try{function Invoke-NxDNative {param([string]$File,[string[]]$Arguments);$script:jobArgs=$Arguments;return '0'};$containers=@{'forensic-postgres'=[pscustomobject]@{Id='db'}};if((Get-NxDActiveJobs $containers)-ne0){throw 'unexpected count'};$sql=[string]$script:jobArgs[-1];if($sql-notlike"*NOT IN ('completed','dead_letter')*"-or$sql-like'*retrying*'){throw "invalid status predicate: $sql"}}finally{${function:Invoke-NxDNative}=$old}}
Record 'http_health_probes_all_services' {$old=${function:Invoke-WebRequest};$script:probeUris=New-Object 'System.Collections.Generic.List[string]';try{function Invoke-WebRequest {param([switch]$UseBasicParsing,$Method,$Uri,$TimeoutSec);$script:probeUris.Add([string]$Uri);return [pscustomobject]@{StatusCode=200}};$cfg=[pscustomobject]@{runtime=[pscustomobject]@{localai_url='http://127.0.0.1:8080'}};Assert-NxDHTTPHealth $cfg;foreach($uri in @('http://127.0.0.1:8091/healthz','http://127.0.0.1:8080/readyz','http://127.0.0.1:8080/','http://127.0.0.1:9109/metrics','http://127.0.0.1:8222/healthz')){if(-not$script:probeUris.Contains($uri)){throw "missing probe: $uri"}}}finally{${function:Invoke-WebRequest}=$old}}
Record 'activated_service_image_and_recreation_gate' {$before=@{api=[pscustomobject]@{Id='old-api'};'forensic-records-api'=[pscustomobject]@{Id='old-fr'}};$after=@{api=[pscustomobject]@{Id='new-api';Image='sha256:new-api';State=[pscustomobject]@{Status='running';OOMKilled=$false}};'forensic-records-api'=[pscustomobject]@{Id='new-fr';Image='sha256:new-fr';State=[pscustomobject]@{Status='running';OOMKilled=$false}}};$expected=@{api='sha256:new-api';'forensic-records-api'='sha256:new-fr'};Assert-NxDServiceImages $before $after $expected $true;$after.api.Image='sha256:wrong';$threw=$false;try{Assert-NxDServiceImages $before $after $expected $true}catch{$threw=$true};if(-not$threw){throw 'wrong candidate image admitted'}}
Record 'protected_service_parity_gate' {$before=@{};$after=@{};foreach($name in @('forensic-records-worker','forensic-postgres','forensic-nats')){$before[$name]=[pscustomobject]@{Id=$name;Image=('sha256:'+$name);RestartCount=0;State=[pscustomobject]@{Status='running';OOMKilled=$false}};$after[$name]=$before[$name]};Assert-NxDProtectedServices $before $after;$after['forensic-nats']=[pscustomobject]@{Id='changed';Image='sha256:forensic-nats';RestartCount=0;State=[pscustomobject]@{Status='running';OOMKilled=$false}};$threw=$false;try{Assert-NxDProtectedServices $before $after}catch{$threw=$true};if(-not$threw){throw 'protected service change admitted'}}
Record 'source_drift_refusal' {$cfg=Get-NxDConfig;$old=${function:Get-NxDHash};try{function Get-NxDHash([string]$p){return 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'};$threw=$false;try{Test-NxDSourceManifest $cfg|Out-Null}catch{$threw=$true};if(-not$threw){throw 'source drift admitted'}}finally{${function:Get-NxDHash}=$old}}
Record 'no_destructive_commands' {$files=@('common.ps1','run_nxb21d_qwen_evaluation.ps1','run_nxb21_bcd_activation.ps1','rollback_nxb21_bcd_activation.ps1');$text=($files|ForEach-Object{Get-Content (Join-Path $PSScriptRoot $_) -Raw})-join"`n";foreach($bad in @('docker system prune','docker image prune','docker volume prune','compose down','--remove-orphans','Stop-Process','taskkill')){if($text.Contains($bad)){throw "forbidden token: $bad"}}}
Record 'go_evaluator_compiles' {$target=Join-Path $root 'api\forensic_records\nxb21d_offline_evaluator_test.go';$cache=Join-Path $root 'local-acceptance-models\nxb21-d\offline-preparation-go-cache';$tmp=Join-Path $root 'local-acceptance-models\nxb21-d\offline-preparation-go-tmp';if(Test-Path $target){throw 'temporary evaluator already exists'};try{New-Item -ItemType Directory -Force -Path $cache,$tmp|Out-Null;$env:GOCACHE=$cache;$env:GOTMPDIR=$tmp;Copy-Item (Join-Path $PSScriptRoot 'd_model_evaluator_test.go') $target;& go test ./api/forensic_records -run '^$' -count=1;if($LASTEXITCODE-ne0){throw 'Go evaluator compile failed'}}finally{Remove-Item $target -Force -ErrorAction SilentlyContinue;Remove-Item Env:GOCACHE,Env:GOTMPDIR -ErrorAction SilentlyContinue}}
Record 'future_evaluator_timeout_and_checkpoint_guards' {$runner=Get-Content (Join-Path $PSScriptRoot 'run_nxb21d_qwen_evaluation.ps1') -Raw;$evaluator=Get-Content (Join-Path $PSScriptRoot 'd_model_evaluator_test.go') -Raw;if($runner-notlike"*'go','test','-v'*"-and$runner-notlike"*go @('test','-v'*" ){throw 'verbose go output missing'};if($runner-notlike"*'-ginkgo.timeout=4h'*"){throw 'Ginkgo timeout override missing'};if($evaluator-notlike'*nxDWriteCheckpoint(outputPath, results, modelCalls, valid)*'-or$evaluator-notlike'*outputPath+".partial"*'){throw 'per-case checkpoint missing'}}
Record 'durable_log_created' {$latest=Get-Content (Join-Path $script:NxPrivateRoot 'latest-activation.json') -Raw|ConvertFrom-Json;if(-not(Test-Path (Join-Path $latest.run_directory 'operator.log'))){throw 'activation refusal did not write a durable log'}}
Record 'stable_exit_codes_documented' {$text=Get-Content (Join-Path $PSScriptRoot 'README.md') -Raw;foreach($n in @(0,10,11,12,20,21,22,23,24,30,40,41,42,43,44)){if($text-notmatch("``$n``")){throw "exit code missing: $n"}}}
$out=[ordered]@{schema_version='nexusai.nxb21d-offline-bundle-test/v1';completed_at=[DateTime]::UtcNow.ToString('o');passed=@($results|Where-Object status -eq 'PASS').Count;failed=@($results|Where-Object status -eq 'FAIL').Count;results=$results}
$path=Join-Path $root 'local-acceptance-models\nxb21-d\offline-bundle-preparation-tests.json';Write-NxDJson $path $out;$results|Format-Table -AutoSize;if($out.failed){exit 1};Write-Host "NXB21D_OFFLINE_BUNDLE_TEST=PASS count=$($out.passed)";exit 0
